# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
    # main version should be kept as close as possible to supported OMV's PHP version
    # and dependencies should be updated with --prefer-lowest to prevent being ahead
    - 7.0

# install project dependencies
install:
    - composer install

jobs:
    include:
        -
            stage: Tests
            name: Lint
            php: 7.0
            script:
                - composer run-script ci-lint
        - &STANDARD_TEST_JOB
            stage: Tests
            name: PHPUnit
            php: 7.0
            script:
                - composer run-script ci-test-unit
